### ISSUE TITLE
Rename data generators from plural to singular

### ISSUE THREAD

**Issue by jariji** [Seelengrab/Supposition.jl#1]
My pet peeve about hypothesis.py is that it uses the plural `booleans()` to generate a single boolean. I think it is easier to understand that a single draw from a generator generates one instance of the thing. For example

```jl
function f(ints)
  sum(ints)
end
```

`f` takes a thing called `ints` which is supposed to be passed a sequence of integers. But `Data.Integers()` will pass it a single integer. I think this is confusing and it would be easier to understand if the way to generate one integer were `Integer()` and, if needed, a shortcut to generate multiple integers were `Integers()`.

A counterargument is that it's more natural for `map` and `filter` to work on things that are named pural.

**Comment by Seelengrab** [comment]
The plural is intentional, since any given generator can generate multiple different instances. The plural also helps prevent punning the existing names like `Vector`, `Dict` and so on, preventing a situation where someone attempts to do `using Supposition.Data: Vector` immediately introducing a name clash with Base.
