### ISSUE TITLE
Rename `assume!` to `assume` 

### ISSUE THREAD

**Issue by jariji** [Seelengrab/Supposition.jl#12]
https://docs.julialang.org/en/v1/manual/style-guide/#bang-convention gives the convention

>Append ! to names of functions that modify their arguments

Since `assume!(::Bool)` doesn't modify its arguments I suspect it should be `assume(::Bool)`.

**Comment by Seelengrab** [comment]
Unlike `rand` (where the hidden state is always assumed to exist), the currently used test case does not always exist, so the bang serves as a reminder that there is *some* (hidden) state being modified when this is called. I'm feeling a bit uneasy about removing the bang there (and similarly with `target!` and `reject!`) too because of that.

It's a bit like `Random.seed!()`, which seeds a (hidden) default.

**Comment by jariji** [comment]
I like having a simple rule with a specific universal documented meaning so authors can use it to communicate simply and precisely to their users. Unfortunately the current "convention" is rather subjective e.g. in `rand(rng)`, `print(io)`, and `seed!(k)`, which makes it hard to use for precise communication between individuals.

Anyway that's just my personal rant, not your problem. Feel free to close this if you like.

**Comment by Seelengrab** [comment]
I'll do a small export-audit of everything that I consider API before registering, so I'll take a look at this then.

**Comment by Seelengrab** [comment]
Alright, I've reworked the exposed API. Everything now consistently uses `<verb>!` from the user-side, to indicate the change of hidden state. I've also modified the internal uses to follow the usual convention.
