### ISSUE TITLE
Have `@composed` assign its `Possibility` to the function name 

### ISSUE THREAD

**Issue by jariji** [Seelengrab/Supposition.jl#13]
```jl
gen_f = @composed function f(x=Data.Floats{Float64}())
  x
end
```

Here we give two different names `f` and `gen_f`. What is the benefit of separating them out like this? Why not just use `f`?

**Comment by Seelengrab** [comment]
Please formulate feature requests with some actionable description instead of as a question - I'm going to look into Github Discussions and/or a zulip channel for general discussion around design decisions.

---

There isn't too big of a reason, other than `@composed` being a slightly more fancy `Map`, defining a new type for dispatch. It makes sense to have this type be the name of the function used for composing, but I guess this can be an implementation detail too.

**Comment by jariji** [comment]
Maybe it's better to keep them separate, so I can still call `f(0.0)` with a normal float instead of a `Possibility`.

**Comment by Seelengrab** [comment]
That doesn't currently work, but could be made to work :thinking: This definitely requires having the function name be distinct from the generator.
