### ISSUE TITLE
Default-argument syntax ambiguity

### ISSUE THREAD

**Issue by jariji** [Seelengrab/Supposition.jl#2]
```jl
Supposition.@check function commutative(a=intgen, b=intgen)
     add(a,b) == add(b,a)
end
```

Normally `b=intgen` would make `intgen` the default argument to the function, but here it's a generator for arguments to the function. What if I actually want to pass a generator as an argument? What does `Supposition.@check function commutative(a=3, b=4)` do -- does it error, requiring a `Just(3)` or what?

It seems ambiguous and potentially confusing. Perhaps it is worth considering alternative syntax, or maybe it'll grow on me.

**Comment by Seelengrab** [comment]
>  What if I actually want to pass a generator as an argument? 

You mean if you want to use `intgen` itself inside of `commutative`? No need; just capture it, or pass a `Data.Just(intgen)`.

> What does Supposition.@check function commutative(a=3, b=4) do -- does it error, requiring a Just(3) or what?

That errors - as documented for `@check`, the arguments are expected to be `Possibility` objects:

```
help?> @check
  @check [key=val]... function...

[...]

  The arguments to the given function are expected to be generator strategies. The names
  they are bound to are the names the generated object will have in the test. These
  arguments will be shown should the property fail!
```

> It seems ambiguous and potentially confusing. Perhaps it is worth considering alternative syntax, or maybe it'll grow on me.

I'm happy about any suggestions, but I'm struggling to come up with anything better than `=`, which clearly communicates assignment (of some form). `::` doesn't work, since that's type assertion.

**Comment by jariji** [comment]
> I'm struggling to come up with anything better than =, which clearly communicates assignment (of some form). :: doesn't work, since that's type assertion.

Yeah. `∈`/`in` comes to mind but I'm not sure whether it's actually better.

**Comment by Seelengrab** [comment]
Right - those also have the disadvantage of being either unicode, or requiring whitespace surrounding the operator. That's not good either, because it means this is harder to type, and the whitespace makes the entire invocation quite a bit longer. Having to write out `function` for the inline-definition style is already quite bloaty, especially when a few config options are passed, so I'd rather avoid forcing the arguments to be passed in longer form as well.
