### ISSUE TITLE
[Doc]: Unexplained jargon

### ISSUE THREAD

**Issue by moble** [Seelengrab/Supposition.jl#35]
### Which part of the documentation is this related to?

This package seems great, and I'm excited to give it a try.  But there are several words that seem to relate to simple concepts, but are never really explained, making it unclear what exactly I can expect from this package.  Specifically, the words "shrinking", "fuzzing", and "invariant" come to mind.

The biggest one is "shrinking", which is used [right from the start](https://seelengrab.github.io/Supposition.jl/stable/index.html):

> shrinking of examples, which can smartly shrink initial failures to smaller example while preserving the invariants the original input was generated under

In other places throughout the docs, you glance at defining it.  [For example](https://seelengrab.github.io/Supposition.jl/stable/intro.html#What-is-Property-Based-Testing?):

> [once a failure is found], reducing it to something we humans can more easily use to pinpoint the uncovered bug, through a process called "shrinking".

[and](https://seelengrab.github.io/Supposition.jl/stable/Examples/docalignment.html#Does-it-error?)

> Supposition.jl will [...] [try to shrink the input to the minimal example] that reproduces the same error.

But I have no idea what metric I use to define a "minimal" example, or what my simple human mind could fail to comprehend.  My first thought was that Supposition would somehow try to eliminate optional arguments or keywords.  I suppose I've found an explanation [here](https://propertesting.com/book_shrinking.html#_shrinking), but something similar in this package's docs would be helpful.  But I'll note that this very sensible definition is in tension with what I guess from the quotes above.

At one point, the docs also *seem* to [equate shrinking with fuzzing](https://seelengrab.github.io/Supposition.jl/stable/interfaces.html#API-for-controlling-fuzzing).  Again, I consult [that other package's docs](https://propertesting.com/book_property_based_testing_tools.html#_in_general) and find an explanation that doesn't seem consistent with what's being used here.

The word "invariant" also comes up almost immediately.  When I do find [some uses that give me context](https://seelengrab.github.io/Supposition.jl/stable/Examples/stateful.html#Juggling-Jugs), it seems like an invariant is just a property.  Is there some distinction that makes those different?

### How could this be communicated better?

It seems to me that the "Main Page" should have a nice paragraph right near the top that introduces a few of these terms, as a way of introducing the topic, and motivating why people should want to use this approach generally (as well as this package specifically).

**Comment by Seelengrab** [comment]
Thanks for opening this issue! I've responded to parts of the issue out-of-order, which hopefully makes the explanation flow better :)

--

> there are several words that seem to relate to simple concepts, but are never really explained, making it unclear what exactly I can expect from this package. Specifically, the words "shrinking", "fuzzing", and "invariant" come to mind.

For shrinking, I've previously posted an explanation and why it's hard to define that succinctly/precisely without getting into the weeds of things [here](https://discourse.julialang.org/t/ann-propcheck-jl/101481/22?u=sukera) - I can add a section like that to the docs, if that helps?

Would a sort of glossary that is linked from the various places the jargon is used help?

> The word "invariant" also comes up almost immediately. When I do find [some uses that give me context](https://seelengrab.github.io/Supposition.jl/stable/Examples/stateful.html#Juggling-Jugs), it seems like an invariant is just a property. Is there some distinction that makes those different?

Yes, that's fair - I'll add a note explaining what an invariant is to those docs. In a nutshell, an invariant is a property that _always_ holds true  (or in other words, must never be broken). For example, a generator like `map(x -> 2x, Data.Integers{Int}())` guarantees that all outputs will always be even; that is, we say that "the objects produced by the generator observe the invariant `x % 2 == 0`."

> I suppose I've found an explanation [here](https://propertesting.com/book_shrinking.html#_shrinking), but something similar in this package's docs would be helpful. But I'll note that this very sensible definition is in tension with what I guess from the quotes above.

From my reading, it's consistent with what I call "shrinking" too; the main difference is that Supposition.jl can shrink well even without additional types, because the shrinking is implied from the generation process. It's one of the main differences (and, in my view, advantages) of Supposition.jl over Quickcheck-like frameworks.

Is the tension you're seeing with this paragraph?

> In such frameworks, whatever information ends up not encodable in the type system (such as a collection being ordered, a tree that is expected to be balanced, a UUID in string form that should be case insensitive, and so on) needs to be specified as shrinking rules.

If so, yes there's tension - you don't need special shrinking rules to make UUIDs (even in string form) shrink well in Supposition.jl. PropEr needs those rules because it's based on QuickCheck, which Supposition.jl is not. For example:

```julia
julia> using Supposition, UUIDs

julia> hex = Data.SampledFrom(collect("abcdef0123456789ABCDEF"));

julia> uuid_string = map(Data.Vectors(hex; min_size=32, max_size=32)) do v
           a = join(@view v[1:8])
           b = join(@view v[9:12])
           c = join(@view v[13:16])
           d = join(@view v[17:20])
           e = join(@view v[21:32])
           join((a,b,c,d,e), '-')
       end;

julia> @check uuidstr_caseinsen(u=uuid_string) -> UUID(uppercase(u)) == UUID(lowercase(u));

Test Summary:     | Pass  Total  Time
uuidstr_caseinsen |    1      1  0.1s
```

Here, we construct a rather complicated string out of 32 mixed-case alphanumeric characters, joining them into a string that's seperated at various points by a `-`. During shrinking, this is an invariant

```julia
julia> uuid = map(UUID, uuid_string);

julia> @check allnonzero(u=uuid) -> all(!=('0'), string(u));
┌ Error: Property doesn't hold!
│   Description = "allnonzero"
│   Example = (u = UUID("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa0"),)
└ @ Supposition ~/Documents/projects/Supposition.jl/src/testset.jl:292
Test Summary: | Fail  Total  Time
allnonzero    |    1      1  0.0s
```

(The property is nonsensical in the context of UUIDs, but I hope this illustrates the point!)

Of course, constructing UUIDs from strings only serves to fuzz the parser employed by the UUIDs package - if I were to test a package that takes UUIDs, I'd much prefer to just give the `UUID` constructor an `UInt128`, since that will be much faster than parsing strings (if possible - some UUIDs require parsing from strings, or creation with a specific timestamp. 
 For those, you can't get around the complexity of creating them).

> At one point, the docs also seem to [equate shrinking with fuzzing](https://seelengrab.github.io/Supposition.jl/stable/interfaces.html#API-for-controlling-fuzzing). Again, I consult [that other package's docs](https://propertesting.com/book_property_based_testing_tools.html#_in_general) and find an explanation that doesn't seem consistent with what's being used here.

Hmm - could you elaborate on this, what exactly you think is inconsistent? The section you're linking is not equating the two, but rather stating that parts of that API are relevant for different "stages" of the entire process.

When I write "fuzzing", I mainly refer to the generation of examples. At that point, there is pretty much no additional information that Supposition.jl (or QuickCheck or most other property based testing frameworks) has, so "generate some random stuff and throw it at the thing" is pretty much the only approach left. I guess one distinction between "true fuzzing" and what I'm doing in this package is that the structure of the input is preserved, which isn't traditionally the case for fuzzing tools (they rather try to discover that structure themselves, with mixed results). Having the randomness limited in this way is, in my view, a big advantage compared to "true fuzzing".

"shrinking" then refers to the process of minimizing a found counterexample to a (in some vague sense, dependent on the generators chosen to generate it) smaller counterexample that makes the property under test fail in the same way.

**Comment by Seelengrab** [comment]
> I don't know if this is right, but maybe something like this:

Yes, for the examples you gave, the explanations are a-priori (for the generators defined by default) correct.

> Hm. An invariant is a subclass of property and always holds true, so in general a property doesn't have to hold true?

When I say "invariant", I'm talking about the [mathematical concept of invariance](https://en.wikipedia.org/wiki/Invariant_(mathematics)). I wouldn't think of invariance itself as being in some sort of hierarchy.

A property alone may be true or false - it depends on the context you're asking the question in. For example, the property $\forall x \in T : x < 256$  is true for `T == UInt8` (here, the property is also an invariant for `UInt8`, because it holds for all $x$), but false for `T == UInt16`. The property $\exists x \in T : x < 0$  is true for `T == Int8` but false for `T == UInt8`. It's not an invariant for `Int8` though because there are $x$ for which $x < 0$ is false.

When you're generating a value through e.g. `gen = Data.Integers{UInt8}()`, the objects generated from `gen` are _guaranteed_ to always be `UInt8`, and thus _guaranteed_ to always be in the closed interval $[0, 255]$ (that's a property of the `UInt8` type). If you now map `x -> 0x2 * x` over `gen` (e.g. `doubleGen = map(x -> 0x2 * x, gen)`), you are _guaranteed_ that the resulting numbers are not only from that interval (because of modulo arithmetic, so `0x80 * 0x2 == 0x00`), but also even. That is, the combined generator observes the property $\forall x \in doubleGen : iseven(x) \land 0 \leq x \leq 255$. (I'm using $x \in doubleGen$ as a shorthand for "all values that could be produced by `doubleGen`"; $\land$ is logical conjunction, i.e. `&&`)

> After reading those passages, I thought shrinking meant eliminating optional or keyword arguments and/or somehow tracing through the code to help narrow down where the difference between passing and non-passing values originated. This, of course, seemed like nonsense, but I couldn't figure out the truth just from the docs.

Indeed, eliminating optional and/or keyword arguments alone doesn't make much sense (though you can also do that, if you so wish). However, Supposition.jl is indeed a tool for narrowing down what exact(ish) input causes a test to fail.

I'm a bit confused how the notion that Supposition.jl is for eliminating optional arguments comes up though - I don't think my docs show anything of the sort?

> Ah. To me, just the use of a slash in the phrase "the shrinking/fuzzing process" implies that those are two words for essentially the same thing.

I see - I'll reword that to clarify what I meant!

> Interesting. Here, I don't understand what you mean by "structure".

Traditional fuzzers like [AFL](https://github.com/google/AFL) treat the input they're generating as an opaque stream of bytes. Any additional structure, like instantiations of certain datastructures or specific formats an input file to the fuzzing target must have (like [magic bytes](https://en.wikipedia.org/wiki/List_of_file_signatures) used to identify file formats) must be discovered by the fuzzer itself. This is not the case with Supposition.jl, because you can compose generators that already produce the correct format. When AFL shrinks/modifies its generated input, it has no general knowledge about hard requirements (such as those magic bytes) and may try examples that must trivially fail, resulting in wasted computing resources. Supposition.jl on the other hand can guarantee that whatever invariants the individual generators provide, also hold true in the composed generator. Further, it also guarantees that any shrunk examples _also_ uphold those invariants.

So if you, for example, always prepend those magic bytes to make your file valid, or need your data in a specific format (such as with UUID above), Supposition.jl can _guarantee_ that this will always be the case, and you can focus on actual problems that come up with structurally-ok, but still bad input (or it might be good input, in which case you've found a bug in your code).
