### ISSUE TITLE
[UX]: Test failures hidden when run as script

### ISSUE THREAD

**Issue by nhz2** [Seelengrab/Supposition.jl#42]
### What happened?

When running a test script that uses Supposition.jl, the outputs are hidden.

Here is the script, "test.jl":
```julia
using Supposition

@check function foo(x=Data.Integers{Int}())
    false
end
```

Using `Supposition@0.3.1` I get:
```sh
(base) nathan@p3070:~/supposition_test$ julia +1.10 --project test.jl
┌ Error: Property doesn't hold!
│   Description = "foo"
│   Example = (x = -9223372036854775808,)
└ @ Supposition ~/.julia/packages/Supposition/KpGkN/src/testset.jl:292
Test Summary: | Fail  Total  Time
foo           |    1      1  0.1s
```

However, when I upgrade to `Supposition@0.3.3` I get no output:
```sh
(base) nathan@p3070:~/supposition_test$ julia +1.10 --project test.jl
(base) nathan@p3070:~/supposition_test$ 
```

### What did you expect to happen?

I expect some message to be printed that a test is failing.

### Julia Version

```shell
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_PKG_DEVDIR = /home/nathan/juliadev
  JULIA_PKG_USE_CLI_GIT = true
```

### Package Environment

```shell
Status `~/supposition_test/Project.toml`
  [5a0628fe] Supposition v0.3.3
```

**Comment by nhz2** [comment]
In case it is relevant,
OS: Linux Mint 21.2 x86_64
Shell: bash 5.1.16
Terminal: gnome-terminal

**Comment by Seelengrab** [comment]
Thanks for the issue! This is because the new printing doesn't unconditionally print anything, unlike the old printing approach that leaned on `Test.Testset`. The new printing is based on `show`, which is called automatically when used in the REPL, but not when used in a script :thinking: The old printing doesn't have a nice `show` method (just like `Test.Testset`...), which is why you (used to) get this huge blob of unhelpful information in the REPL after execution in 0.3.1:

![image](https://github.com/Seelengrab/Supposition.jl/assets/11753998/4b9a4d9a-92ed-4e0d-a571-55f354beb8a3)

I could change this to always manually invoke `show`, but I'm unsure how good that will work when used interactively - I'd like not to `show` the report twice :sweat_smile: Unfortunately, `Test` requires me to return the custom `AbstractTestset` used by Supposition.jl from the outermost invocation, so preventing that double printing is quite a challenge..

**Comment by nhz2** [comment]
Oh I see, putting the `@check` in a `@testset` fixes the issue. Thanks.

```julia
using Supposition
using Test

@testset "foo" begin
    @check function foo(x=Data.Integers{Int}())
        false
    end
end
```

```sh
(base) nathan@p3070:~/supposition_test$ julia +1.10 --project test.jl
Found counterexample
  Context: foo

  Arguments:
      x::Int64 = -9223372036854775808
Test Summary: |Time
foo           | None  3.2s

```

**Comment by Seelengrab** [comment]
Yep, that works because `@testset` just always prints, and `@check` shows itself if it's in another `@testset` (since then the object isn't returned to the REPL for printing).

IMO this should be fixed with a more general design decision upstream, deciding what exactly should happen with `AbstractTestset` and its printing. It's not very friendly to always print unconditionally :/ Perhaps `Test.Testset` could be transitioned to `show` too, with some mechanism to facilitate printing when executed as a script? Supposition.jl could then hook into that.

**Comment by Seelengrab** [comment]
I've opened an upstream issue about this problem, let's see if we can get input from other people https://github.com/JuliaLang/julia/issues/54766
